import { NextResponse } from 'next/server';
import { generateSitemaps } from '../sitemap';

const BASE_URL = 'https://dreamboatjournal.com';

export async function GET() {
    // Dynamically retrieve the exact chunks generated by sitemap.ts
    // This perfectly synchronizes the custom index with the native chunks and prevents 5xx/404s
    const chunks = await generateSitemaps();

    let sitemaps = '';
    for (const chunk of chunks) {
        sitemaps += `  <sitemap>\n    <loc>${BASE_URL}/sitemap/${chunk.id}.xml</loc>\n  </sitemap>\n`;
    }

    const xml = `<?xml version="1.0" encoding="UTF-8"?>
<sitemapindex xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">
${sitemaps}</sitemapindex>`;

    return new NextResponse(xml, {
        headers: {
            'Content-Type': 'application/xml',
            'Cache-Control': 'public, max-age=86400, s-maxage=86400',
        },
    });
}
